[package]
name = "simple-nwu-year-paper"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Easecond"]
license = "MIT"
description = "西北大学学年论文 Typst 模板。 | An academic year paper template for Northwest University (China), built with Typst."
repository = "https://github.com/Easecond/nwu-academic-year-paper"
keywords = ["Northwest University", "Paper"]
categories = ["paper"]
